<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3jrxbX8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3jrxbX8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3jrxbX8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3jrxbX8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3jrxbX8\App_KernelDevDebugContainer([
    'container.build_hash' => '3jrxbX8',
    'container.build_id' => '9702597a',
    'container.build_time' => 1630929829,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3jrxbX8');
